### ISSUE TITLE
Write a script to do all of the data cleaning and save results.

### ISSUE THREAD

**Issue by youngant** [adam-broussard/bestreads#20]
Because the English recognition (and probably some other features soon to come) is slow, a cleaned version of the data CSV needs to be saved to disk.

**Comment by adam-broussard** [comment]
Is this better done in a Jupyter notebook?  I think that "cleaning the text" is a high-level concept, so it might be a good idea to put everything into a notebook so we can explain all of the steps instead of wrapping them all into a single script.  Alternatively we could do both a wrapper script and a demonstration of the individual steps :)

**Comment by youngant** [comment]
I have no problem with a notebook if it's dedicated to downloading/cleaning the data (and it's probably better for the reasons you mention). The reason for the script suggestion was to avoid having the downloading/cleaning take place at the top of an analysis notebook, where we would then have to wait a while when starting up the notebook fresh.

**Comment by adam-broussard** [comment]
Sounds good to me - we'll do both :)

**Comment by youngant** [comment]
I forgot to address this when I closed #33. We still have the issue that starting the analysis notebook means rerunning `text.is_english()` and `text.clean_text()`, which takes several minutes. This should be fixed by swapping the order of the "Train-Test Set Splits" and "Text Cleaning" sections in the preprocessing and adding `english_descriptions` and `cleaned_descriptions` to the CSVs that get saved out. Using those later can just be done by getting the appropriate columns from the CSV in the analysis notebook.

**Comment by youngant** [comment]
Nevermind, I got confused by the fact that the analysis notebook just hadn't been updated yet. I think just reading in `goodreads_books_train_processed.csv` at the top of that notebook should work.
