### ISSUE TITLE
Fix data directory in  notebooks

### ISSUE THREAD

**Issue by youngant** [adam-broussard/bestreads#35]
The notebooks are looking for data in `notebooks/data/` rather than `data/`. They just need a `../`at the beginning of paths.

**Comment by adam-broussard** [comment]
I did this on purpose, but we can put the data directory in the root directory if you'd like :)

**Comment by adam-broussard** [comment]
I should also mention that the present structure was the result of #10

**Comment by youngant** [comment]
I forgot about #10. I just got confused since there were two different data directories. I'm okay with leaving things the way they were originally. Would it maybe be less confusing to have something like a "rawdata" directory?
