### ISSUE TITLE
Reduce Noise

### ISSUE THREAD

**Issue by adam-broussard** [adam-broussard/bestreads#37]
I think we are going to have to pare down our genres further...  I have just finished writing a query function, and I am finding that a huge number of genres don't have very many associated books, leading to cases where we overfit because there is, e.g., only one book in the "Productivity" genre and it mentions the word "time" more than once, so it dominates any query that mentions "time".  Approximately 100 genres have <10 associated books.

**Comment by adam-broussard** [comment]
I should also mention that running the [query function](https://github.com/adam-broussard/bestreads/blob/bd123608ec679bbd8bff36eb2803d0c018b7627f/bestreads/text.py#L301) with `weight_scheme=1` seems to help somewhat in my preliminary testing.

**Comment by youngant** [comment]
Maybe it's worth setting `weight_scheme=1` to the default?

One thing we could do is just drop all genres with too few books. The figure below suggests 25 books is a good cutoff. This means dropping 119 genres (see list below).

![71aae8c3-cd85-43a2-8f25-28266547c9b9](https://user-images.githubusercontent.com/38996442/165209741-f77f5780-cd91-4f84-a4db-f9b616a89cb1.png)
(Sorry, axes background is transparent and doesn't show up well in dark mode.)

Dropped genres:
['Christianity', 'Environment', 'Sociology', 'Drama', 'Occult',
       'Suspense', 'World War II', 'Shapeshifters', 'Anthologies',
       'Games', 'Leadership', 'Mythology', 'Computer Science',
       'Anthropology', 'Polyamorous', 'Lds', 'Adult', 'Marriage',
       'Relationships', 'Academic', 'Fan Fiction', 'Esoterica',
       'Dungeons and Dragons', 'Inspirational', 'Comics', 'Book Club',
       'Science Fiction Fantasy', 'Football', 'Couture', 'Apocalyptic',
       'Epic', 'Military History', 'Fairy Tales', 'Category Romance',
       'Audiobook', 'Gardening', 'Law', 'Asian Literature', 'Family',
       'Sexuality', 'Architecture', 'Medical', 'Love', 'Design', 'Combat',
       'Space', 'Pseudoscience', 'American', 'Biology', 'Prayer',
       'Novella', 'Race', 'Aviation', 'Gothic', 'Unfinished',
       'Disability', 'Criticism', 'Modern', 'Textbooks',
       'Magical Realism', 'Humanities', 'Action', 'Military', 'Nurses',
       'Womens', 'Biography Memoir', 'Central Africa', 'Diary',
       'New York', 'Manga', 'Pop Culture', 'Witchcraft', 'Spy Thriller',
       'Kids', 'Mental Health', 'Dc Comics', 'Currency', 'Gamebooks',
       'Crafts', 'True Story', 'Gender', 'Teaching',
       'Speculative Fiction', 'Linguistics', 'Social Issues', 'Computers',
       'Romantic', 'Folk Tales', 'World Of Warcraft', 'Fairies',
       'Harlequin', 'Pornography', 'Alcohol', 'Female Authors',
       'Neuroscience', 'Biblical Fiction', 'Buisness', 'Eastern Africa',
       'Roman', 'Futuristic', 'Productivity', 'School Stories', 'Church',
       'Gay Romance', 'African Literature', 'Nobel Prize',
       'Northern Africa', 'Family Law', 'Menage', 'Own', 'Polyamory',
       'North American Hi...', 'Superheroes', 'Nature',
       'Political Science', 'Warfare', 'Sci Fi Fantasy',
       'Paranormal Urban Fantasy', 'Love Inspired']

**Comment by adam-broussard** [comment]
That makes sense to me.  It would be really nice if we had a way of grouping genres, because a lot of these sound like bigger genres with slightly different phrasing (for example 'Dc Comics' should fit under 'Comics').  In practice, putting in the effort to reduce these by hand may not actually improve our dataset that considerably though.

**Comment by youngant** [comment]
Agreed. Combining these will still result in pretty small genres. There are probably only ~500 books total across all of these genres. 

Also, here's the list of genres that still remain: 

'Fantasy', 'Fiction', 'Romance', 'Young Adult', 'Nonfiction',
'Historical', 'Mystery', 'Science Fiction', 'Sequential Art',
'Childrens', 'Classics', 'Horror', 'History', 'Poetry',
'Paranormal', 'Philosophy', 'Thriller', 'Religion',
'Christian Fiction', 'Short Stories', 'Biography', 'Christian',
'New Adult', 'Science', 'Womens Fiction', 'Cultural', 'Business',
'Humor', 'Plays', 'Media Tie In', 'Psychology', 'Autobiography',
'Self Help', 'Animals', 'Sports', 'Erotica', 'Spirituality', 'Art',
'Contemporary', 'Dark', 'Adult Fiction', 'Music', 'Politics',
'Travel', 'Adventure', 'Realistic Fiction', 'Crime', 'LGBT',
'Economics', 'Food and Drink', 'Novels', 'Holiday', 'Westerns',
'Parenting', 'War', 'Urban', 'Language', 'GLBT', 'Feminism',
'Health', 'Literature', 'Amish', 'European Literature', 'Culture',
'Reference', 'Education', 'Writing'

Now that the list isn't so large, we might want to do a little bit of tweaking them by hand to clean up the predictions. For example, I think "GLBT" is the same as "LGBT" (but we should double check). Also, maybe "Fiction" should be renamed to something like "General Fiction" so our predictions look less naive.

**Comment by adam-broussard** [comment]
If we want, we could REALLY pare down the genres to about 20 and then manually assign every single unique genre in the dataset to one of those.  This would make the classification problem much simpler and less granular.  Some ideas for this could be using Goodreads' default genres (below) or Barnes & Noble's most popular subject list (further below).
![image](https://user-images.githubusercontent.com/33520634/165342742-03c0985c-f905-4fdf-902d-f18928d53011.png)
![image](https://user-images.githubusercontent.com/33520634/165343097-084d64fd-0bf5-4772-961f-f4e706467d21.png)

**Comment by adam-broussard** [comment]
One thing to keep in mind also is that many books have multiple genres that are good descriptors (at least if we aren't operating on a really high level like the lists above), so the fact that we are basing our analysis on the single top genre by votes may be improvable by incorporating the top *N* genres instead somehow.

**Comment by youngant** [comment]
I'm not really sure what we should do. I'm not sure that every "genre" we have matches up easily with one of the categories from Goodreads or Barnes & Noble, and I kind of like the range of genres we have. That being said, I think  manually messing with them somewhat would be good. Honestly, I'm pleasantly surprised at how sensible the "genres" are given the way they are generated by Goodreads.

I'm pretty interested to see how the multi-genre prediction would work. I'd vote that we at least see what those predictions look like before deciding how to further manipulate the list we have.

**Comment by adam-broussard** [comment]
At least with our current setup, we could modify the current query function to output the top N genres instead of the top 1 - that would be a quick implementation.  I'll also make an issue to create a function that runs on the test data and outputs some results.

**Comment by youngant** [comment]
Okay, I understood it the way you had meant it then. See new issues #42 and #43.
