### ISSUE TITLE
Need a requirements.txt

### ISSUE THREAD

**Issue by youngant** [adam-broussard/bestreads#8]
This can be generated with `pipreqs /path/to/project/`.

**Comment by adam-broussard** [comment]
Are these meant to be dependencies?  Do we need to turn this into a package for this to work?

**Comment by adam-broussard** [comment]
Okay, so this is just documentation?  It's not actually anything that gets fed into code anywhere (unless you chose to create a new environment to run our code)?  I'm just not familiar with it, so I want to make sure I understand, but it sounds reasonable.
